language: java

jdk:
  - openjdk7

sudo: false

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
# matrix-start
    - R_CHECK_PACKAGES=""
# matrix-end

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - "export DISPLAY=:99.0"
  - "export PATH=$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH"
  - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - texinfo

cache:
  directories:
  - $HOME/bin
  - $HOME/R
  - $HOME/texlive

install:
  - "[ ! -d ~/bin ] && mkdir ~/bin || true"
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e 'devtools::install_deps(dep = TRUE)'

# summon crandalf!
script:
  - ./inst/scripts/install-texlive
  - R -e "sapply(.libPaths(), list.files, simplify=F)"
  - ./inst/scripts/install-pandoc
  - cd ..; R CMD build crandalf && R CMD INSTALL crandalf_*.tar.gz; cd crandalf
  - ./inst/scripts/crandalf
  - "[ $TRAVIS_BRANCH == master ] && R CMD check --no-manual ../crandalf_*.tar.gz || true"
