language: java

jdk:
  - openjdk7

env:
  global:
    - R_LIBS_USER=~/R R_TEXI2DVICMD=texi2dvi _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
# matrix-start
    - R_CHECK_PACKAGES=""
# matrix-end

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get -qq update
  - ./inst/scripts/install-texlive
  - ./inst/scripts/install-pandoc
  - sudo apt-get -qq install r-base-dev
  - sudo apt-get autoremove
  - "[ ! -d ${R_LIBS_USER} ] && mkdir ${R_LIBS_USER}"
  - sudo R CMD javareconf
  - cd .. && R CMD build crandalf
  - R CMD INSTALL crandalf_*.tar.gz
  - cd crandalf

# summon crandalf!
script:
  - ./inst/scripts/crandalf
  - "[ $TRAVIS_BRANCH == master ] && R CMD check --no-manual ../crandalf_*.tar.gz || true"
